apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
  labels:
    app: db
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # password (base64 encoded)
  MYSQL_DATABASE: ZGF0YWJhc2U=      # database (base64 encoded)
  MYSQL_USER: YWRtaW4=              # admin (base64 encoded)
  MYSQL_PASSWORD: YWRtaW5wYXNz      # adminpass (base64 encoded)
